### ISSUE TITLE
2 hands model can not predict well on one hands image

### ISSUE THREAD

**Issue by lucasjinreal** [Dw1010/IntagHand#3]
how to resolve this problem?

**Comment by ZhengdiYu** [comment]
> how to resolve this problem?

Do you have any qualitative results?

**Comment by ZhengdiYu** [comment]
I think for current version, the output is fixed to 2 hand.

**Comment by lucasjinreal** [comment]
No, I am just wonder is this model issue or all such model issue, it just can not distinguish 2 hands or 1 hand.

Also, wonder if a model train on 1 hand, how does it predict on 2 hands coupled togather.....

**Comment by ZhengdiYu** [comment]
> No, I am just wonder is this model issue or all such model issue, it just can not distinguish 2 hands or 1 hand.
> 
> Also, wonder if a model train on 1 hand, how does it predict on 2 hands coupled togather.....

1. It's just an issue of this kind of pipeline, you will need **an extra hand detector to crop the hands, also, using the detector to distinguish whether it's 2 hands or 1 hand**. You need to adapt the code from scratch to fit in your single hand case. Current code's logic of this paper only supports two hands interaction occasion.

2. If a model was only trained on left hand, when you met a right hand, you will have to flip the image and regard it as a left hand. Also, if the two hands are interacting closely, you would have to use the same image patch for both hands. 

3. Just to notice: if the two hands are too far from each other, for example one hand touching your face, another hand touching your belly. In this case, directly cropping the whole upper body and resize to 256 will result in very bad results, you need to crop each individual hand and regress them seperately. It's quite tricky when you should crop the whole hand region or crop individual hand.

**Comment by lucasjinreal** [comment]
@ZhengdiYu thank u. so in practical scene, we must using a classifier or something to judge, whether current image crop is 1 hand or 2 hand? If 1 hand, we have also judge it's left or right? if 2 hand, then we need send to 2 hand model, if 1 hand, we send to 1 hand model.

Is there any model can handle then all in one?

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu thank u. so in practical scene, we must using a classifier or something to judge, whether current image crop is 1 hand or 2 hand? If 1 hand, we have also judge it's left or right? if 2 hand, then we need send to 2 hand model, if 1 hand, we send to 1 hand model.
> 
> Is there any model can handle then all in one?

Actually you can use 2 hand model as well. Because the output is fixed, for example, you can disable the output for left hand when there is only right hand detected

**Comment by lucasjinreal** [comment]
@ZhengdiYu I tried 2 hand model on single hand, the output either left nor right predicted right.. it was mess, don't know why

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu I tried 2 hand model on single hand, the output either left nor right predicted right.. it was mess, don't know why

I think there should always be two hands presented in the image. If you didn't change the code at all.

**Comment by lucasjinreal** [comment]
> Actually you can use 2 hand model as well. Because the output is fixed, for example, you can disable the output for left hand when there is only right hand detected

I know the code is impressive on 2 hand scenarios. I test it on purpose on single hand only scene. Seems it can not handle both of it. So this is the original question at the begaining, We seems can not actually one model rule them all.

**Comment by ZhengdiYu** [comment]
> > Actually you can use 2 hand model as well. Because the output is fixed, for example, you can disable the output for left hand when there is only right hand detected
> 
> I know the code is impressive on 2 hand scenarios. I test it on purpose on single hand only scene. Seems it can not handle both of it. So this is the original question at the begaining, We seems can not actually one model rule them all.

Well, I see what you mean, but I have tested on single-hand image without any change to the code, it seems reasonable. Could you post some of your results for single hand?

**Comment by lucasjinreal** [comment]
@ZhengdiYu Am using webcam, and place my single hand at front of my laptop, it seems, however, might because of my hands too big at the fixed rectangle? Can u post how did u test on single-hand image and result ? I might try using detector to crop since the fix box is very rough

**Comment by ZhengdiYu** [comment]
I just did a simple test on some video, using a detector to get the box in advance.

![image](https://user-images.githubusercontent.com/63605407/163098088-fcc6f868-8f4d-45c1-a392-181ef1487874.png)
![image](https://user-images.githubusercontent.com/63605407/163098156-717c7bfc-8cae-4619-ba96-f2fae9f91b6a.png)
![image](https://user-images.githubusercontent.com/63605407/163098197-77f11f4c-a4db-4f10-ad98-c15f92826632.png)

Although there is an extra blue left hand as I didn't adapt the code. But the red one looks reasonable

**Comment by lucasjinreal** [comment]
@ZhengdiYu does there a way to remove the blue hand? i mean, how do we know which hand should left

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu does there a way to remove the blue hand? i mean, how do we know which hand should left

Yes there is. You should use a detector to justify which side you should remove.

**Comment by lucasjinreal** [comment]
@ZhengdiYu On the other hand, does there is a threshold to do so?

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu On the other hand, does there is a threshold to do so?

I don't know what you mean by 'threshold'. 

But I think a normal hand detector can easily tell you which hand is in the image. You don't need a 'threshold' to do so. Just looking at which hand's bounding box is presented in the detection results should be enough for your purpose.

**Comment by lucasjinreal** [comment]
@ZhengdiYu You produce two hands, without any threshold for either hand?

> Just looking at which hand's bounding box is presented in the detection results

The question is, detector either won't know, if the box is 1 hand or 2 hands.... It can be 1 or 2 on one single box.

**Comment by ZhengdiYu** [comment]
> @ZhengdiYu You produce two hands, without any threshold for either hand?
> 
> > Just looking at which hand's bounding box is presented in the detection results
> 
> The question is, detector either won't know, if the box is 1 hand or 2 hands.... It can be 1 or 2 on one single box.

I don't think a normal hand detector won't know whether it's left hand or right hand.

It should be something like this:
![image](https://user-images.githubusercontent.com/63605407/163778180-e00b571e-3c0c-495a-8184-082cfce4b0c7.png)

If the two hands is severely interacting, then the two boxes will also be severely overlapping, in this case, just crop the region for two hands.

Just like I said before. This work has a drawback: you would never know when to crop to individual hand to process like a single-hand reconstruction work, or when to crop the whole region for two hands. As it's a very blur definition for 'interacting'. From my point of view, I think you can compute the 'iou' of the left hand box and right hand box, if it's bigger than a threshold, you can take the whole region

Anyway, if the two hands are separated for a 'long' distance, you should crop the individual hand and process them separately.

**Comment by lucasjinreal** [comment]
> I don't think a normal hand detector won't know whether it's left hand or right hand.

I mean 1 hand or 2 hand.... not left or right..

**Comment by ZhengdiYu** [comment]
> > I don't think a normal hand detector won't know whether it's left hand or right hand.
> 
> I mean 1 hand or 2 hand.... not left or right..

大佬你可以用中文再复述一遍, 可能我没太理解你的意思
